spring:
  datasource:
    generate-unique-name: false
    name: tcpserverdb
    url: jdbc:postgresql://localhost:5432/tcpserverdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
   com.laiz.tcpserver: debug
   org:
    springframework:
      orm.jpa: DEBUG
      transaction: debug
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: info
