spring:
  datasource:
    generate-unique-name: false
    name: tcpserverdb
    url: jdbc:postgresql://localhost:5432/tcpserverdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.laiz.tcpserver: info
    org:
      springframework:
        orm.jpa: info
        transaction: info
      hibernate:
        SQL: info
        type.descriptor.sql.BasicBinder: info
